---
- hosts: localhost
  gather_facts: no
  become: yes
  tasks:
    - name: Donwload git repo
      ansible.builtin.git:
        repo: https://github.com/oferwess/Voyager_Labs_Task.git
        dest: /root/git_repo

    - name: create build directory
      file:
        path: /dockerbuild
        state: directory
        owner: root
        group: root
        mode: '0755'
#    - name: copy Dockerfile and depndencies
#      copy:
#        src: /root/git_repo/flaskapp/
#        dest: /dockerbuild
#        owner: root
#        group: root
#        mode: '0644'
    - name: copy Dockerfile and depndencies
      command: cp -r /root/git_repo /dockerbuild
    - name: build container image
      docker_image:
        name: flaskapp:v1.0
        build:
          path: /dockerbuild/dockerfile
          source: build
        state: present
