---
- name: Build-Playbook
  hosts: all
  remote_user: centos
  gather_facts: yes
  vars:
   current_user: "{{ ansible_env.USER }}"
  become: yes
  tasks:

    - name: Prune everything
      docker_prune:
        containers: yes
        images: yes
        networks: yes
        volumes: yes
        builder_cache: yes
      ignore_errors: yes

    - name: Uninstall docker pip python package
      ansible.builtin.pip:
        name: docker
        state: absent
      ignore_errors: yes

    - name: Uninstall docker, git, pyhon
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - git 
          - python3
          - python3-pip
        state: absent
      ignore_errors: yes
      
    - name: Deleting /var/lib/docker
      shell: rm -rf /var/lib/docker
      args:
        warn: no
      ignore_errors: yes

    - name: Set up docker repository
      shell: |
        dnf install -y yum-utils
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        warn: no

    - name: Install Docker, git, pyhon and pip packages
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - git 
          - python3
          - python3-pip
        state: latest
        update_cache: true

    - name: Install docker pip python package
      ansible.builtin.pip:
        name: docker

    - name: Add the current user to the docker group
      user:
        name: "{{ current_user }}"
        groups: docker
        append: yes

    - name: Start and enable docker
      shell: |
        sudo systemctl start docker
        sudo systemctl enable docker 

    - name: create git repo directory
      file:
        path: /flaskapp
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Donwload git repo
      ansible.builtin.git:
        repo: https://github.com/oferwess/flaskapp-task.git
        dest: /flaskapp

    - name: Log into DockerHub
      docker_login:
        username: "{{ lookup('ansible.builtin.env', 'DOCKER_HUB_USERNAME') }}"
        password: "{{ lookup('ansible.builtin.env', 'DOCKER_HUB_PASSWORD') }}"
      retries: 3

    - name: build container image
      docker_image:
        build:
          dockerfile: dockerfile 
          path: /flaskapp
        state: present
        source: build
        name: oferwess/flaskapp
        tag: v1.0
        push: yes